name: karaoke_request_api
description: The API for the Karaoke Request Client
version: 1.9.1
publish_to: https://dart.pkg.jetbrains.space/flup/p/main/flup/

environment:
  sdk: '>=2.17.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.2
  pretty_dio_logger: ^1.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.0.0
